### ISSUE TITLE
Liens Streamaway inutilisables.

### ISSUE THREAD

**Issue by joaopa00** [Sphinxroot/IPTVM3U#11]
Les liens Streamaway ont maintenant des jetons. Il est impossible de les utiliser dans une liste m3u8.

**Comment by Sphinxroot** [comment]
salut  .. faudrais savoir lequels car tout les liens qui ont tracks-v1a1/mono.m3u8 avec le referer fonctionne pour moi dans kodi seulement et ne sont pas formater pour les autres applications .

les liens qui sont de bestserver ont toujours ete avec jeton et jai pas le temps de les changers a chaque jours ,ce pourquoi ils ne sont plus inclut dans les listes pour l instant  .. les liens avec tag (UPD)  sont justement des liens a mise a jours journalieres et je ne garantie pas la dure de ces liens
