### ISSUE TITLE
Quebec.m3u

### ISSUE THREAD

**Issue by kevin465** [Sphinxroot/IPTVM3U#12]
Ce matin beaucoup de chaine de fonctionne plus...

**Comment by Sphinxroot** [comment]
oui https://www.streamaway.net/  semble etre mort , la pluspars des liens viennent de la ,alors y a pas grand chose que je puisse faire  pour le moment  ..  je cherche une autre option ou site qui re-stream

**Comment by kevin465** [comment]
Ah d'accord merci pour l'information et merci beaucoup quand-même pour cette merveilleuse application 🙂
