### ISSUE TITLE
TNT et streamaway

### ISSUE THREAD

**Issue by Sphinxroot** [Sphinxroot/IPTVM3U#14]
tout les liens de https://www.tntendirect.com/  ont maintenant un jeton de 30minutes

et https://www.streamaway.net/  semble mort  ou a ete saisi  domage

**Comment by mikhoul** [comment]
Y'a longtemps j'avais un script PHP qui allait récupérer  le jeton et regénérait l'url avec le jeton.

Donc dans ma playlist je pointait vers l'url PHP qui elle générait l'url pour streamer. Ex.: https://s7.tntendirect.com/arte/live/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9OC8yNC8yMDIxIDI6MzE6MzkgQU0maGFzaF92YWx1ZT1iMzEzQ2tmREFjaEhIYlpxRW5SYk9nPT0mdmFsaWRtaW51dGVzPTMw


Dans ce temps-ci je n'ai pas le temps de mettre ne place un serveur mais au moins je sais que c'est faisable, on inclus dans la liste M3U le lien du canal (liens PHP) qui lui retournera dynamiquement le lien avec le jeton.

**Comment by Sphinxroot** [comment]
oui jy avais penser egalement mais jai pas le temps de monter et maintenir un serveur streamlink pour restreamer les sources , jai deja peine a maintenir le tout a jours ici , sans compter la 20aines de projets arreter pour le moment

deja je suis pris entre continuer qua faire du direct play  ou completement changer ma tele direct avec le guide ou en xml pour y inclure du regex mais le probleme est de faire fonctionner d autre addon dans le xml  ce qui m obligera a changer toute les listes

depuis la fermeture de streamaway  je me fais harceler sur FB lol  , a la longue je risque d abandonner le projet
quand c est pas du monde qui te disent que ca vaut rien vue que c est pas du HD ou FHD , 4k sans guide et j en passe .. 
ah oui et le fait quil ne sois pas compatible matrix ... alors quils peuvent prendre playlistloader pour matrix et mettre les liens raw en remote ...

perso j utilise un mini pc beelink alors jai les 2 kodi d installer , 1 en portable l autre en normal , de plus tu peut runner BlueStacks pour les apks et avoir RetroArch pour le retro gaming , alors que le monde ne jure que  sur firestick ou  shield

je l avais fait pour moi a la base  , mais le monde pense que je suis un service  ... 

t inkiet je chiale pas , je constate  lol

bonne journe mik

**Comment by mikhoul** [comment]
Laisse aller le monde.... 😉

Je fais mes projets perso et quand ils sont potables je les partage ici ou sur d'autres forums. Pour les demandes qui n'ont pas d'allure et/ou impolie ne répond pas tout simplement.  Quand c'est constructif ça vaut le coup de répondre mais autrement c'est la galère.

J'utilise une TC-Box Nexbox A95X et ça fait la job pour moi, elle est rooté alors j'ai le contrôle. J'utilise présentement Perfect Player mais dès que j'aurai un peu de temps je vais migrer vers TiviMate car il supporte les "referer"/userAgent à la manière des playlist de Kodi.

Pour mes amis qui n'ont pas de TV-Box j'installe souvent [IPTVNATOR]( https://github.com/4gray/iptvnator) car il est disponible sous Windows, Mac et Linux et il supporte lui aussi les referer et user-agent.

Pour le serveur avec TNT direct je pensais pas à un serveur avec streamlink mais plutôt à un script PHP qui contient les commandes pour aller loader la page du canal que tu veux écouter et qui "parse" le code avec un regex pour avoir l'URL avec le jeton et qui une fois qu'il l'a output l'url avec le jeton.

Avec cette stratégie ça ne consomme pas beaucoup de bande passante, par contre il faut faire une page "PHP" pour chaque canal car l'url de la page que va "parser" le script sera différente pour chaque canal,

Quand j'aurai plus de temps je vais sans doute le faire et je le laisserai la source ici, c'est tellement léger que ça peut même s'héberger sur un serveur gratuit qui supporte le PHP ou encore un serveur local et ça serait mieux pour ne pas que la même IP ping sans arrêt  "TNT Direct" et soit banni.

De cette façon c'est plus facile à maintenir que "restreamer" et moins énergivore en ressources, y'a des changements à faire seulement si le format de l'URL et du token change pour la REGEX.

Bonne fin de journée ou soirée à toi :octocat:

**Comment by Sphinxroot** [comment]
https://www.streamaway.net/  de retour mais pas tout les liens fonctionnent

**Comment by mikhoul** [comment]
As-tu un lien @Sphinxroot  pour ABXplore ?  Ou même un site qui le stream et que je pourrais écouter **depuis le Canada** ? 


Salutations :octocat:

**Comment by Sphinxroot** [comment]
> As-tu un lien @Sphinxroot pour ABXplore ? Ou même un site qui le stream et que je pourrais écouter **depuis le Canada** ?
> 
> Salutations :octocat:

A date non rien de concluant appart des xtream-codes et streamaway encore sur le dos  quand ca va bien .. ca va bien 

au plaisir :)
