### ISSUE TITLE
Orange url....

### ISSUE THREAD

**Issue by aldo7410** [Sphinxroot/IPTVM3U#2]
Hello,
thank you very much for your list of French channels
the urls ( cdn.webtv4.cdnfr.orange.fr ) work very well and if you have others, do not hesitate, 
but it is already enormous, on the other hand the other French server does not work any more pity .....
(9ef693e4a1c9995c5003732394002e98.streamhost.cc/)
Thank you again and good luck to you .....

**Comment by Sphinxroot** [comment]
hello :)  for streamhost.cc/ they are hard to maintain  and will probably left them down   i got new link but they work for some time  they arrent stable , i need to find other sources for them  .. just like youtube  links they change offten ..

**Comment by Sphinxroot** [comment]
if you want them download them and intall it localy https://www.sendspace.com/file/jqkd5q

**Comment by aldo7410** [comment]
Hello my friend,
thank you very much for your answer, it's very nice to have sent me the links ....
After various tests with the orange tv links, I realized that for those which are of bad quality like Boomerang for example, it is enough to change the end, replace 01 by index and the quality goes to HD ...... Boomerang_live /01.m3u8..........Boomerang_live/index.m3u8
I am looking for these urls because they work great ......
  while doing tests, I found 2 new orange stream channels,
I will not fail to keep you informed if it interests you dear friend ......
Thank you very much and good work ...
See you soon.....

**Comment by locka-hd** [comment]
where i can find all the link cdn.webtv4.cdnfr.orange.fr in website or box
