### ISSUE TITLE
Pluto tv

### ISSUE THREAD

**Issue by aldo7410** [Sphinxroot/IPTVM3U#3]
Hello, Pluto tv will arrive in French version at the beginning of February, do you think you will be able to have it ?????
Thank you very much for your posts dear friend and good luck to you .....

**Comment by Just4dashow** [comment]
Le lun. 1 févr. 2021 8:12 a.m., aldo7410 <notifications@github.com> a
écrit :

**Comment by Sphinxroot** [comment]
they will be online the 8th of FEB  and will be added to the list ;-)

**Comment by aldo7410** [comment]
Hello and thank you for your answer dear friend .... good luck to you and good luck in your work .....

**Comment by Just4dashow** [comment]
Sorry man ... witch  link i have to take for the QUEBEC channel ?!?

Sorry 4 that but im a real noob ahahhah thanks cya
