### ISSUE TITLE
Zatoo.tv

### ISSUE THREAD

**Issue by aldo7410** [Sphinxroot/IPTVM3U#4]
Hi friend and thank you for your work and sharing ....
I was wondering if it was possible to have Zatto.tv channels like the Swiss TSR ????? Thank you again and good luck to you ....

**Comment by Sphinxroot** [comment]
hi  .. thank for the request  .. but unfortunately i cant .. first  the free service its 30hr limited  .. second geoblock so vpn needed , third the stream are token and expirable link  , if u need it u might consider   kodi whit the  zattoo box plugin or the pvr   if you have a account and vpn on

**Comment by aldo7410** [comment]
Hello and thank you friend for your precious information, good luck to you .....
