### ISSUE TITLE
Novoo Link does not work anymore

### ISSUE THREAD

**Issue by Evilmnkey** [Sphinxroot/IPTVM3U#5]
Hi, just FYI Novoo link is not working today

#EXTINF:-1 tvg-logo="https://github.com/Sphinxroot/plugin.video.iptv.free/raw/master/Images/Logo%20Station%20QC/NOOVO.png?raw=true" group-title="Quebec TV",Noovo (V-Tele)
https://bcsecurelivehls-i.akamaihd.net/hls/live/551061/618566855001/master.m3u8

**Comment by Sphinxroot** [comment]
yeah working on it :/

i got this for now 


#EXTINF:-1,noovo audio
https://pe-fa-lp03a.9c9media.com/live/NOOVO/p/hls/00000201/716cf4c845225692/manifest.m3u8


#EXTINF:-1,noovo video 720p
https://pe-fa-lp03a.9c9media.com/live/NOOVO/p/hls/00000201/716cf4c845225692/index/de22f34f/live/stream/h264/v1/3500000/manifest.m3u8

#EXTINF:-1,noovo video 720p
https://pe-fa-lp03a.9c9media.com/live/NOOVO/p/hls/00000201/716cf4c845225692/index/de22f34f/live/stream/h264/v2/3500000/manifest.m3u8

**Comment by dreambox43** [comment]
salut  dans les chaines  belgique les VTM  ne fonctionne plus

**Comment by Sphinxroot** [comment]
> salut dans les chaines belgique les VTM ne fonctionne plus et dans les française tout les lien orange on tous un soucis aurais tu d autre sources pour les FR et BE j ai moi même un serveur iptv et j ai un peux de mal sur les ciné + canal + et sources orange Merci
> 
> Voici mon skype live:christelle378

je vais verifier ce weekend .. jai tester quelque lien orange .. appart canal+  les autres sembles fonctionner , pour les VTM  normalement c des postes premium alors je ne saurrais dire si le serveur a changer les liens
