### ISSUE TITLE
Thirteenth street francais ...

### ISSUE THREAD

**Issue by joaopa00** [Sphinxroot/IPTVM3U#6]
#EXTINF:-1 tvg-id="France" tvg-name="13ème rue"  tvg-logo="https://upload.wikimedia.org/wikipedia/fr/thumb/7/76/13e_rue_2010_(logo).svg/220px-13e_rue_2010_(logo).svg.png" group-title="France", 13ème rue
https://www.streamaway.net/fra/13e/mono.m3u8|Referer=https://www.streamaway.net/fr/13erue-fr.php

**Comment by Sphinxroot** [comment]
Merci  @joaopa00  Ajouter  a la liste .. la derniere fois il y avait pas de flux dispo
