### ISSUE TITLE
Histoire

### ISSUE THREAD

**Issue by joaopa00** [Sphinxroot/IPTVM3U#7]
#EXTINF:-1 tvg-id="France" tvg-name="Histoire TV"  tvg-logo="https://histoire.fr/sites/default/files/histoire_logo_0.png" group-title="France", Histoire TV
https://www.streamaway.net/fra/histo/index.m3u8|Referer=https://www.streamaway.net/fr/Histoire-fr.php

**Comment by Sphinxroot** [comment]
Merci @joaopa00  ajouter a la liste
