### ISSUE TITLE
liens morts

### ISSUE THREAD

**Issue by joaopa00** [Sphinxroot/IPTVM3U#8]
mpv **http://185.180.15.16:2200/EX/FR_W9_HD-fr/tracks-v1a1/mono.m3u8?token=RED_eN3emca1W8GXeL7VSY93_Q%3D%3D%2C1622483196.0546341468**
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://185.180.15.16:2200/EX/FR_W9_HD-fr/tracks-v1a1/mono.m3u8?token=RED_eN3emca1W8GXeL7VSY93_Q%3D%3D%2C1622483196.0546341468.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

Exiting... (Errors when loading file)

mpv **http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/hd1-850464/hls/index.m3u8**
[ffmpeg] tcp: Failed to resolve hostname cdn.webtv4.cdnfr.orange.fr: Temporary failure in name resolution
Failed to open http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/hd1-850464/hls/index.m3u8.
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution'))) 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

mpv **http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/tech_tf1_ott_mobile-155120/hls/index.m3u8**
[ffmpeg] tcp: Failed to resolve hostname cdn.webtv4.cdnfr.orange.fr: Temporary failure in name resolution
Failed to open http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/tech_tf1_ott_mobile-155120/hls/index.m3u8.
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution'))) 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

mpv **http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/tvbreizh-27323/hls/04.m3u8**
[ffmpeg] tcp: Failed to resolve hostname cdn.webtv4.cdnfr.orange.fr: Temporary failure in name resolution
Failed to open http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/tvbreizh-27323/hls/04.m3u8.
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution'))) 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

mpv **http://212.224.98.211:2200/EX/CARTOON_NETWORK-fr/tracks-v1a1/mono.m3u8?token=RED_SGEtOt_dtiq_cWp16lPA1Q%3D%3D%2C1622237921.8132941117**
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://212.224.98.211:2200/EX/CARTOON_NETWORK-fr/tracks-v1a1/mono.m3u8?token=RED_SGEtOt_dtiq_cWp16lPA1Q%3D%3D%2C1622237921.8132941117.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

Exiting... (Errors when loading file)

 mpv **http://212.224.98.210:2200/EX/HISTOIRE-fr/tracks-v1a1/mono.m3u8?token=null**
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://212.224.98.210:2200/EX/HISTOIRE-fr/tracks-v1a1/mono.m3u8?token=null.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

Exiting... (Errors when loading file)

mpv **http://212.224.98.211:2200/EX/FR_WARNER_TV-fr/tracks-v1a1/mono.m3u8?token=RED_pzNUYP99Zb1_I6BiMe00Jw%3D%3D%2C1622238623.7165478160**
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://212.224.98.211:2200/EX/FR_WARNER_TV-fr/tracks-v1a1/mono.m3u8?token=RED_pzNUYP99Zb1_I6BiMe00Jw%3D%3D%2C1622238623.7165478160.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

Exiting... (Errors when loading file)

mpv **http://185.180.15.15:2200/EX/13EME_RUE-fr/tracks-v1a1/mono.m3u8?token=null**
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://185.180.15.15:2200/EX/13EME_RUE-fr/tracks-v1a1/mono.m3u8?token=null.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

Exiting... (Errors when loading file)

mpv **http://185.180.15.15:2200/EX/MANGA-fr/tracks-v1a1/mono.m3u8?token=null**
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://185.180.15.15:2200/EX/MANGA-fr/tracks-v1a1/mono.m3u8?token=null.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

mpv **http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/live/Rtl9_live/index.m3u8**
[ffmpeg] tcp: Failed to resolve hostname cdn.webtv4.cdnfr.orange.fr: Temporary failure in name resolution
Failed to open http://cdn.webtv4.cdnfr.orange.fr/hs/HALO3/hls/live/Rtl9_live/index.m3u8.
[ytdl_hook] ERROR: Unable to download webpage: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution'))) 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

mpv **http://212.224.98.204:2200/EX/USHUAIA_TV-fr/tracks-v1a1/mono.m3u8?token=RED_SGEtOt_dtiq_cWp16lPA1Q%3D%3D%2C1622237921.8132941117**
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://212.224.98.204:2200/EX/USHUAIA_TV-fr/tracks-v1a1/mono.m3u8?token=RED_SGEtOt_dtiq_cWp16lPA1Q%3D%3D%2C1622237921.8132941117.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

mpv **http://212.224.98.209:2200/EX/FR_C8_HD-fr/tracks-v1a1/mono.m3u8?token=RED_eN3emca1W8GXeL7VSY93_Q%3D%3D%2C1622483196.0546341468**
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://212.224.98.209:2200/EX/FR_C8_HD-fr/tracks-v1a1/mono.m3u8?token=RED_eN3emca1W8GXeL7VSY93_Q%3D%3D%2C1622483196.0546341468.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

mpv **http://212.224.98.212:2200/EX/ANIMAUX-fr/tracks-v1a1/mono.m3u8?token=null**
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://212.224.98.212:2200/EX/ANIMAUX-fr/tracks-v1a1/mono.m3u8?token=null.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

mpv **http://212.224.98.211:2200/EX/ACTION-fr/tracks-v1a1/mono.m3u8?token=null**
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://212.224.98.211:2200/EX/ACTION-fr/tracks-v1a1/mono.m3u8?token=null.
[ytdl_hook] ERROR: Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. 
[ytdl_hook] youtube-dl failed: unexpected error ocurred 

Exiting... (Errors when loading file)

**Comment by Sphinxroot** [comment]
merci  retirer temporairement .. d autre v ont etre ajouter sous peu
